### ISSUE TITLE
Decouple dependencies and parameters in dependencies.g

### ISSUE THREAD

**Issue by ssiccha** [lbfm-rwth/GaussPar#143]
E.g. ClearDownParameters is used to schedule calls of ClearDown. In the `..Parameters` we set up the dependencies for ClearDown and also call `TaskResult` to get the parameters for the ClearDown call. But `TaskResult` implicitly waits on its argument. So before we schedule a call we already wait on all of its dependencies.

Unless I'm missing something that doesn't really make sense.

Since we're setting up destructive versions of each subprogram, we may even be able to get rid of the parameters part in the `..Parameters` functions completely, that is we only handle the dependencies there.

**Comment by jnkbrachter** [comment]
Done by #191
