### ISSUE TITLE
Add a "glueing" function

### ISSUE THREAD

**Issue by ssiccha** [lbfm-rwth/GaussPar#153]
There is code in `Chief` that glues the blocks of R and K. Let's put that into a new function and get it out of `Chief`.

I'm not sure how much code is shared between glueing R and K. Maybe we can even make a single function out of it.

**Comment by emmakatherina** [comment]
I think we need to glue R and M, is that right?

**Comment by ssiccha** [comment]
Hmm, it looks like M is glued together and this becomes B, R is glued and becomes C, K is glued and becomes D. This is currently in the last blocks of `Chief`.
