### ISSUE TITLE
Make sure all matrices are in compressed representation

### ISSUE THREAD

**Issue by ssiccha** [lbfm-rwth/GaussPar#168]
In particular `NullMat` and `IdentityMat` don't create compressed matrices. If we use these matrices in later calculations these results will be also not be in compressed matrix representation but they become read-only once we return them.

I'm patching most of the functions, but this is currently violated by the glueing code in `Chief`. I'm not sure whether we can assume that the relevant matrices don't contain rows that are empty lists, since `ConvertToMatrixRep` will fail if that's the case.

**Comment by ssiccha** [comment]
There are some places in the `Glue..` functions where we can't yet turn matrices into a compressed matrix.

**Comment by ssiccha** [comment]
The reason that they aren't compressed matrices yet is that we can't do `A{list1}{list2} := .. ` for compressed matrices. To fix this we should use `CopySubMatrix`, see #187.

**Comment by ssiccha** [comment]
#187 is closed now. The only thing that remains to do is to find alternatives for `IdentityMat` and `NullMat` in `GAUSS_GlueFromBlocks`.

Also I should double check each function that it really only uses 8bit or cvec matrices.

**Comment by jnkbrachter** [comment]
IdentityMatrices are now beeing generated in compressed representation everywhere.
Note that there is currently no way of generating a compressd NullMat in GAP.
