### ISSUE TITLE
choose a better name for ChiefParallel

### ISSUE THREAD

**Issue by ReymondAkpanya** [lbfm-rwth/GaussPar#22]

**Comment by ssiccha** [comment]
ATM `ChiefParallel` is the main function of the package. We should use a more descriptive name. Probable use the same name from the gauss package and just add a `Parallel` at the end.

**Comment by emmakatherina** [comment]
EchelonMatTransformationParallel? Any other suggestions or should I implement this?

**Comment by ssiccha** [comment]
Sounds good :+1:

**Comment by ssiccha** [comment]
Although, I think better would be DoEchelonMatTransformationParallel. DoXXX is the usual name for the algorithm that does the actual work. Then there usually are several functions providing wrappers for the user.

E.g. here we could also want a function like EchelonMatParallel, by which I mean a function that does not compute a transformation matrix.

**Comment by ssiccha** [comment]
Updated suggestion: `DoEchelonMatTransformationBlockwise`
