### ISSUE TITLE
Get rid of global vars in measure_contention.g

### ISSUE THREAD

**Issue by ssiccha** [lbfm-rwth/GaussPar#27]

**Comment by AnnaKDS** [comment]
Ich arbeite daran.

**Comment by emmakatherina** [comment]
@AnnaKDS Arbeitest du daran noch oder soll ich das übernehmen? :)

**Comment by AnnaKDS** [comment]
Du kannst das gerne übernehmen.

**Comment by emmakatherina** [comment]
Get rid of global variables, make it one big function and add documentation.

I would like to work on this in the next weeks.
