### ISSUE TITLE
Unite parallel and sequential version in one file

### ISSUE THREAD

**Issue by emmakatherina** [lbfm-rwth/GaussPar#38]
More specific: Unite main_full_par_trafo.g and main_seq_trafo.g. Do this by adding functions (for example for each step and each version) that get selected depending on the version that is defined in a boolean.

I would like to work on this in the next 2 weeks.

**Comment by emmakatherina** [comment]
Don't forget to adjust the test files!

**Comment by ssiccha** [comment]
Also : make the boolean `parallel` as an optimal argument. If it is not given, detect whether GAP or HPC-GAP is loaded.
