### ISSUE TITLE
Add option whether the transformation matrix should be computed

### ISSUE THREAD

**Issue by emmakatherina** [lbfm-rwth/GaussPar#50]

**Comment by emmakatherina** [comment]
Should we still adress this?

**Comment by ssiccha** [comment]
Definitely. We now have the wrappers `EchelonMatTransformationBlockwise`, and `EchelonMatBlockwise` but `DoEchelonMatTransformationBlockwise` still always computes the trafo matrix AFAIK.

Let's wait until we finish #118 to not add another layer of if branches to the main function.

**Comment by jnkbrachter** [comment]
Has been fixed by #161
