### ISSUE TITLE
Rewrite sequential code before Step 2

### ISSUE THREAD

**Issue by emmakatherina** [lbfm-rwth/GaussPar#53]
There are some for loops where some entries are overwritten several times, although we already have the final value.

Also, maybe we dont even need to store the results in extra lists.

**Comment by emmakatherina** [comment]
@jnkbrachter will have a look

**Comment by ssiccha** [comment]
The mentioned code was removed some time ago. Namely when we introduced the `_destructive` versions of the functions in `gap/tasks.g`
