### ISSUE TITLE
Add function to verify output via transformation matrix

### ISSUE THREAD

**Issue by ssiccha** [lbfm-rwth/GaussPar#54]
If a transformation matrix was computed one could check the computation by applying the transformation matrix and checking whether the result is in row reduced echelon form.

One could pass a `verify := true` option to our main function which runs the verification after the algorithm itself. This would very comfortably increase the trustworthiness of our results a lot. HPC-GAP is still alpha. Even it weren't this is still a multi-threaded program.

**Comment by emmakatherina** [comment]
This should also be a documented function.

**Comment by emmakatherina** [comment]
Arguments: mat, transformation mat
Multiply and check whether the result is in a reduced row echelon form.
Return true or false.

**Comment by emmakatherina** [comment]
I think that I need to wait for PR #150 to be in the master branch before starting to work on that.

**Comment by ssiccha** [comment]
Fixed in #179.
