### ISSUE TITLE
Get rid of "redundant" ScheduleTask calls

### ISSUE THREAD

**Issue by ssiccha** [lbfm-rwth/GaussPar#6]
In `main_full_par_trafo.g` e.g. [lines 148 - 229] there are several almost identical `ScheduleTask` calls. The reason is that if e.g. a `ClearDown` in the first row is scheduled (line 165) there is no previous `ClearDown` it depends on. Compare this to line 207 where both a dependency on the `ClearDown` task is given (the task is stored in the list of lists `TaskListClearDown`) and the result of this task is used via `TaskResult`
Instead one could do a single `ScheduleTask` call for e.g. `ClearDown` and one for `Extend` by having a special function which prepares the arguments for the `ScheduleTask` call.

Hopefully, this enables us to have small diffs between the sequential and the parallel versions of the main files.

**Comment by emmakatherina** [comment]
I am working on that.
