### ISSUE TITLE
Merge DoEchelonMatTransformationBlockwise and Chief

### ISSUE THREAD

**Issue by ssiccha** [lbfm-rwth/GaussPar#86]
Currently we have wrappers for `DoEchelonMatTransformationBlockwise`, which itself is a wrapper for `Chief`. Let's merge these two. One layer of wrappers is enough.

**Comment by emmakatherina** [comment]
Do you want to put the content of the function Chief into the file main.gi?

**Comment by ssiccha** [comment]
See issue #166.

**Comment by ssiccha** [comment]
Fixed in #194
