### ISSUE TITLE
Introduce arguments numberBlocks and blockSizes

### ISSUE THREAD

**Issue by ssiccha** [lbfm-rwth/GaussPar#89]
IMO `DoEchelon...` should have a possible argument `numberBlocks` and a possible argument `blockSizes` with different meanings! The first one is the number of blocks we use, the second one is the size of each block which then determines the numberBlocks we need.

The first one is easier to reason about a la "I have 4 cores, let me chop it up into 4 x 4 blocks". I think the latter is better to optimize. If the blocks and the ground field are "too small", the task framework is not able to start the scheduled jobs quickly enough. This only depends on the block size and the field size.

**Comment by ssiccha** [comment]
Rather call them `numberBlocks` and `blockSizes`.

**Comment by ssiccha** [comment]
This should be done for `DoEchelonMatTransformationBlockwise` and its wrappers.

**Comment by ssiccha** [comment]
Work on this was started in #97.

**Comment by ssiccha** [comment]
Our idea is to have a function that computes the `numberBlocks..` from the options record.

There we should also catch whether e.g. `numberBlocks` is bigger then the number of rows or columns of the matrix.

**Comment by ssiccha** [comment]
We will not implement `numberBlocks`.

**Comment by jnkbrachter** [comment]
Introduced numberBlocks as possible argument
